### ISSUE TITLE
Vues catalogues / Volets filtres

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#110]
Lorsqu'on sélectionne un filtre ça recharge la page et ça referme la famille de filtres dans laquelle on l'avait sélectionné, en affichant le filtre sélectionné en haut du volet en dehors des familles. 

En parallèle j'ajoute un bouton "Tout désélectionner" en dessous des familles de filtres pour le bouton reset dans les maquettes.

Est-ce qu'il est possible de plutôt reprendre le principe de la maquette : quand on clique sur un filtre, il passe en état sélectionné dans la famille à laquelle il appartient et la disposition des familles ne bouge pas (pas de fermeture de la famille en question), exemple ci-dessous et [testable dans le volet filtres ici](https://www.figma.com/proto/QMRA56yNNHfvbhEXdibNYK/Passe-UI?page-id=1555%3A33832&type=design&node-id=2367-45470&viewport=2955%2C1077%2C0.22&t=ueHWOvz7uQ8Oq3u6-1&scaling=min-zoom&starting-point-node-id=2367%3A45470&mode=design)

![image](https://github.com/noesya/ecotheque/assets/37301562/f5dd1d36-674e-45ed-a247-b93ce8e48bef)

**Comment by pabois** [comment]
Au moins rouvir les filtres sélectionnés ?

**Comment by flogll** [comment]
Rouvrir la/les famille(s) du/des filtre(s) sélectionné(s) ? Si possible c'est l'idéal

**Comment by SebouChu** [comment]
C'est bon pour avoir le volet ouvert quand une valeur est sélectionnée, j'ai un p'tit truc à régler au niveau des ancres avant de fermer l'issue

**Comment by SebouChu** [comment]
Cacher la partie "selected" qui fait doublon
