### ISSUE TITLE
[Mobile] Vignettes (catalogues et renvois fiches)

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#115]
On a choisi de ne pas afficher les tags sur mobile dans les catalogues avec les vignettes pour éviter des pages à rallonge et aussi pour éviter d'avoir trop de tags longs tronqués.

Prod
![image](https://github.com/noesya/ecotheque/assets/37301562/29d9fdd2-5508-4077-aea9-b05fd0310f12)

Maquette
![image](https://github.com/noesya/ecotheque/assets/37301562/10c379d7-65ba-4758-95cc-aaf2e59c18e1)

**Comment by Olivia206** [comment]
Fait sur la branche [fixes](https://github.com/noesya/ecotheque/pull/105)
