### ISSUE TITLE
Roue de Brezet qui disparait

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#128]
Sur ma config (MBP 15 2018 / macOS 14.1.1 / Firefox 123.0.1) la roue de brezet se réduit à gauche puis disparait vers le haut au lieu de rester en sticky au scroll

![image](https://github.com/noesya/ecotheque/assets/37301562/fed1061d-adfb-4f64-b94a-9cdbc0e2e287)
![image](https://github.com/noesya/ecotheque/assets/37301562/6631d355-190e-432f-b6e5-229c5575e14d)
![image](https://github.com/noesya/ecotheque/assets/37301562/2689ade2-395e-4da8-8937-0ec0d3ea6abb)

**Comment by pabois** [comment]
Même problème sur mon mac avec chrome
