### ISSUE TITLE
L'ordre de tri par défaut des annuaires doit être anté-chronologique

### ISSUE THREAD

**Issue by pabois** [noesya/ecotheque#134]

**Comment by arnaudlevy** [comment]
ça va nous ramener aux tris multiples ça

**Comment by arnaudlevy** [comment]
c'est une idée douteuse je trouve

**Comment by pabois** [comment]
comment ça ? Y'a déjà des tris multiples @arnaudlevy, sur les 4 annuaires. C'est juste changer l'ordre par défaut
