### ISSUE TITLE
Fiche écosystème : Indiquer qu'il s'agit d'un format carré sous la photo

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#139]
Dans le back office, sur les fiches écosystème, sur la photo principal.
Sous "image", il y a déjà le texte "Fichiers .jpg, .jpeg, .png, .svg uniquement. 5 Mo max."
Ajouter "format carré"

**Comment by pabois** [comment]
@Arthur-VilletteMakerz

**Comment by Arthur-VilletteMakerz** [comment]
On parle bien de la photo principale ?
Exemple de la photo de Annabel, elle est rectangulaire dans le BO et carré dans le front.
L'idée est juste d'indiquer dans le BO que l'image en ligne sera carrée
<img width="306" alt="Capture d’écran 2024-03-19 à 12 00 54" src="https://github.com/noesya/ecotheque/assets/163397728/164804c7-ca01-417e-94cd-5b13ad7075d9">
<img width="347" alt="Capture d’écran 2024-03-19 à 12 00 49" src="https://github.com/noesya/ecotheque/assets/163397728/c2ea59d7-4208-46a3-b7de-ae0f33dbc968">

**Comment by Arthur-VilletteMakerz** [comment]
Ou afficher directement le format carré dans le BO comme ça pas de surprise en ligne

**Comment by pabois** [comment]
si en front on affiche tout le temps l'image en carré, autant permettre de la cadrer comme on le souhaite.
Tu as vu la feature dans l'édition de ton profil ?

**Comment by Arthur-VilletteMakerz** [comment]
Je viens de voir :) 
Ce serait parfait !

**Comment by flogll** [comment]
c'est effectivement tout le temps carré sur le front (vignettes et header fiche)

@pabois tu confirmes que vous ajoutez la feature pour recadrer ? si possible sur toutes les fiches comme le principe vignette et image header est le même pour toutes

**Comment by pabois** [comment]
Oui on va mettre l'outil de recadrage partout.
Par contre ca ne marchera que pour les futur images, pas pour celles déjà entrées

**Comment by flogll** [comment]
yes il faut reuploader c'est ça ?

**Comment by pabois** [comment]
oui !
