### ISSUE TITLE
message “Ce site est considéré par nos services comme potentiellement malveillant”

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#140]
Lors de la confirmation du compte, Le message “Ce site est considéré par nos services comme potentiellement malveillant”
![image](https://github.com/noesya/ecotheque/assets/163397728/6b6484de-bed4-4ede-8ffc-2abbfaf19642)

**Comment by pabois** [comment]
Je n'ai pas de solution simple là. Visiblement le mail a été envoyé par un serveur SendInBlue catalogué par Infomaniak comme "potentiellement malveillant"
