### ISSUE TITLE
Documents disponibles : Possibilité d'ajouter un lien vers une ressource (vidéo, pdf en ligne...)

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#141]

**Comment by pabois** [comment]
@Arthur-VilletteMakerz je n'ai pas compris ce que tu attendais ?

**Comment by Arthur-VilletteMakerz** [comment]
Dans la partie "documents disponibles" 👇

<img width="1255" alt="Capture d’écran 2024-03-20 à 09 25 47" src="https://github.com/noesya/ecotheque/assets/163397728/6ff128f4-612a-47de-bada-8c1313b98042">

Il y a des fois ou nous avons des liens vidéo ou pdf en ligne.
C'est donc pour savoir si il est possible de proposer le choix entre mettre un fichier ou mettre un lien 
Exemple ci-dessous 👇

<img width="776" alt="Capture d’écran 2024-03-20 à 09 36 58" src="https://github.com/noesya/ecotheque/assets/163397728/4168e6b8-17cd-40b2-9dde-86d25cdf5efd">

**Comment by arnaudlevy** [comment]
Non, là c'est pour des documents et ça doit rester clair.
Il faut ajouter les liens dans les textes.
Eventuellement il pourra être nécessaire d'ajouter un nouveau type d'élément "Liste de liens", mais c'est confusant.

**Comment by Arthur-VilletteMakerz** [comment]
Entendu
