### ISSUE TITLE
Bloc images

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#142]
- [x] ajouter upload de jpg sur les blocs images des pages édito (BaO / Le Lab), seuls png pris en compte pour l'instant (sur Firefox / macOS)
- [x] ajouter champs de description du bloc pour être iso maquettes (texte uniquement sinon ils vont faire nimp) et réparer crédits qui ne s'affichent pas pour l'instant même si renseignés. Arriver à ça pour iso maquettes
![image](https://github.com/noesya/ecotheque/assets/37301562/5eb1f1f6-1647-45c4-bc2d-9896e8042c2c)

- [x] pb identifié sur la page [BaO / Travaux lab / Ignifugation](https://www.ecotheque.fr/boite-a-outils/travaux-du-lab/ignifugation-alternatives) : les images sont affichées en galerie et sur fond vert au lieu de carousel sur fond gris 
![image](https://github.com/noesya/ecotheque/assets/37301562/4ba0b3f1-f4ea-482b-872d-5e8e66a42dbf)

**Comment by flogll** [comment]
pb supplémentaires : 

- Dans le BO des fiches écosystème (exemple sur fiche Annabel), il y a bien la possibilité d'ajouter du texte de description (ce que j'ai demandé dans le com précédent) mais il s'affiche à la place des crédits en front

![image](https://github.com/noesya/ecotheque/assets/37301562/bb791bf3-2795-487b-931f-84e6cd5228d7)
![image](https://github.com/noesya/ecotheque/assets/37301562/9097cdb6-3c20-4a29-8ada-f048e8154208)

- [ ] il faut arriver à ça sur l'ensemble des blocs images pour être sûr qu'on est raccord (identique première image premier commentaire)
![image](https://github.com/noesya/ecotheque/assets/37301562/c6850a33-7769-43bb-b515-77495a381455)

**Comment by Olivia206** [comment]
@pabois est-ce qu'il ne faudrait pas ajouter un champ "crédit" au bloc image pour être iso avec la galerie des projets ? (pour l'instant il n'y a que "description alternative" et "légende")

**Comment by pabois** [comment]
oui sans doute !

**Comment by pabois** [comment]
@Olivia206 j'ai ajouté les credits.
Par contre si j'en crois ton code si tu as que 2 images tu affiches pas les credits, c'est normal ?

**Comment by pabois** [comment]
@Olivia206 je t'ai rajouté la description, je te laisse la caler comme il faut

**Comment by pabois** [comment]
@flogll pas de soucis pour moi avec les jpg ? (sur FF, Chrome, Safari)

**Comment by Olivia206** [comment]
Crédits et descriptions sont calés en front (et non ce n'était pas normal, merci)
