### ISSUE TITLE
BO / Points-clés

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#143]
Sélection de texte impossible dans ce champs, ça déplace l'élément (Firefox / macOS)

![image](https://github.com/noesya/ecotheque/assets/37301562/e731b461-6e46-4cbd-8996-93025d96c23a)

**Comment by flogll** [comment]
Par ailleurs, ajouter si possible dans la mention "Fichiers svg uniquement..." : "Veiller à n'utiliser que des îcones de taille 48x48px", sauf si possible de contraindre la taille en front qui serait l'idéal

![image](https://github.com/noesya/ecotheque/assets/37301562/ac44323c-bf05-463b-b211-963a4292d971)

**Comment by pabois** [comment]
@flogll pas de soucis pour moi pour la sélection. Peut-être grâce au passage en rich-text ?
