### ISSUE TITLE
BO / Fiches ecosystème / Section services proposés

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#145]
c'est surement temporaire, il y a encore le champ texte classique et en plus le champ rich text dans la section Services proposés
![image](https://github.com/noesya/ecotheque/assets/37301562/e1393c5a-e1d6-4376-9a13-2c251f009783)

Il faudrait enlever le champ texte classique pour ne laisser que le rich, et remplacr le nom du champ rich par "Texte d'explication" qui est actuellement utilisé pour le champ classique

**Comment by pabois** [comment]
@flogll c'est des éléments de la structure ça.
Tu modifies ?
