### ISSUE TITLE
Rich-text dans les Fiches et dans les blocs éditoriaux

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#146]
Il faudrait enlever la possibilité de changer le style de texte (normal / h3) dans les champs rich-text des fiches (mais laisser le reste) sinon ça risque de faire des résultats bizarres avec les sous-titres en meta déjà prévus (exemple ci-dessous).

Pour les blocs éditoriaux il ne faudrait laisser l'option style de texte que pour les blocs texte et pas pour les autres, et dans l'idéal les aligner sous le titre de bloc comme ça (si surplus pas de soucis pour laisser le h3 à droite au dessus du paragraphe comme actuellement)
![image](https://github.com/noesya/ecotheque/assets/37301562/ce0e2ccd-aea9-483a-91b1-8f06977d2c3a)

**Comment by Olivia206** [comment]
Pour l'instant côté front je ne peux pas faire l'alignement propre titre à gauche et texte à droite

@pabois est-ce qu'on doit revoir la structure du bloc ou on laisse en l'état ?

**Comment by pabois** [comment]
@flogll on revient en arrière alors ? Tu m'avais fait ajouter cette gestion du style précisément pour ces blocs dans les fiches, pour pouvoir faire des titres + paragraphes libres ?

**Comment by pabois** [comment]
donc en résumé :
sur les 4 annuaires les h3 des blocs richtext doivent avoir un style muted
sur les pages de contenu editorial les h3 doivent être des titres plus gros alignés à droite

**Comment by Olivia206** [comment]
@pabois pour être sûre que j'ai bien compris : comme ça pour les pages édito ?

![Capture d’écran 2024-03-21 à 16 41 52](https://github.com/noesya/ecotheque/assets/91660674/d5c7e383-d260-4b39-9a35-1f4c751d7abc)

**Comment by pabois** [comment]
oui !
