### ISSUE TITLE
Fiches non publiées accessibles via le glossaire

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#150]
Les fiches non publiées (comme [Rotor](https://www.ecotheque.fr/ecosysteme/rotor) ou [Cité Source](https://www.ecotheque.fr/ecosysteme/citesource) à l'heure actuelle par exemple) sont accessible si on passe par le glossaire, dans le cas présent par [Sensibilisation](https://www.ecotheque.fr/ecosysteme/prestations-proposees/sensibilisation) par ex. C'est le cas aussi pour les autres annuaires après test.

**Comment by flogll** [comment]
Est-ce que c'est pcq je suis admin ?

**Comment by pabois** [comment]
Non je pense qu'il manque le scope
