### ISSUE TITLE
Ajouter un "trier par" à l'index des régions

### ISSUE THREAD

**Issue by Olivia206** [noesya/ecotheque#151]
Par ordre alpha / ordre alpha inversé

**Comment by pabois** [comment]
C'est un vrai besoin ça ? On n'a pas de filtre pour les régions, on ne va pas se mettre juste un tri étrange ?

**Comment by pabois** [comment]
@Olivia206

**Comment by Olivia206** [comment]
Je ne trouve pas ça très utile non plus à vrai dire !
On peut s'en passer ?

**Comment by pabois** [comment]
Bah oui !

**Comment by Olivia206** [comment]
Ok super je close alors oups
