### ISSUE TITLE
Bug de zoom lors de la sélection du filtre "conception artistique"

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#166]

**Comment by Arthur-VilletteMakerz** [comment]
Il y a un zoom trop fort qui ne permet pas de voir les résultat alors qu'il y en a 3

<img width="1385" alt="Capture d’écran 2024-03-21 à 15 49 30" src="https://github.com/noesya/ecotheque/assets/163397728/81bf0dd5-92f9-4e91-8c34-8eb5f6e5257a">

**Comment by alexisben** [comment]
La carte s'affiche comme s'il n'y avait pas d'acteurs sur la carte, est-ce qu'il y avait un autre filtre activé ? Peux-tu ré-essayer sur la version de production ?  https://www.ecotheque.fr/ecosysteme

**Comment by Arthur-VilletteMakerz** [comment]
Zoom automatique lorsque je clique sur le filtre :
<img width="1380" alt="Capture d’écran 2024-03-21 à 17 23 53" src="https://github.com/noesya/ecotheque/assets/163397728/7438c114-aa18-4d5c-93db-cc2eb1f51565">

Lorsque je dézoom : 
<img width="1375" alt="Capture d’écran 2024-03-21 à 17 24 09" src="https://github.com/noesya/ecotheque/assets/163397728/f4c72a8b-2d7f-45da-91c6-04d3bf9a7e3b">

**Comment by alexisben** [comment]
Ok merci ! J'ai réussi à reproduire dans un certain contexte, je crois qu'on est bon !
