### ISSUE TITLE
Ajouter smooth scroll lors du clic sur une ancre des résultats de recherche

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#177]
![image](https://github.com/noesya/ecotheque/assets/37301562/93773a50-154a-4167-b1d5-c978a675237a)

**Comment by alexisben** [comment]
On a désactiver le smoothscroll pour que le rafraîchissement des filtres ne fassent pas des effets bizarres

**Comment by pabois** [comment]
@flogll ok pour toi, on close ?

**Comment by flogll** [comment]
ah dac pas de soucis
