### ISSUE TITLE
Les blocs des offres ne sont pas fidèles à la maquette

### ISSUE THREAD

**Issue by pabois** [noesya/ecotheque#180]

**Comment by alexisben** [comment]
On devrait être plus proche là : https://www.ecotheque.fr/le-lab/comment-nous-rejoindre

**Comment by flogll** [comment]
yes super merci !

**Comment by flogll** [comment]
juste y'a plus les boutons mais j'imagine que c'est temporaire ?

**Comment by pabois** [comment]
non c'est parce que tu es déjà admin :)

**Comment by pabois** [comment]
déconnecte toi tu verras
