### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by pabois** [noesya/ecotheque#188]
- [x] intégrer le search en haut
- [x] intégrer le CTA en haut
- [x] Corriger le style du bas (on peut maintenant ajouter des blocs sur la page Accueil, mais les blocs de texte font des h2, ça fait pas comme la maquette. Quid ?)

**Comment by flogll** [comment]
juste là dans les champs de texte c'est des h3 non ?

**Comment by pabois** [comment]
Quand on le gérait "à la main" le titre "A propos" était en h2, les titres intermédiaires en h3 à gauche, et les textes en <p> à droite.
Là on reprend la logique des blocs, donc les mêmes styles : le "titre" du bloc est en h2, et ensuite dans la partie droite on alterne entre titre h3 et normal

**Comment by flogll** [comment]
nickel merci !
