### ISSUE TITLE
Bloc éditorial Points clés - Taille icones

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#189]
Possible de contraindre la taille des icones à 48px (hauteur) ? La solution du hint pour encourager à ne pas utiliser d'icones au dessus de cette taille ne suffit pas visiblement 

![image](https://github.com/noesya/ecotheque/assets/37301562/2788a7e6-35cb-48d7-a49c-624da18ebe1a)

**Comment by pabois** [comment]
non pas possible en l'état (je peux rajouter des contraintes sur un élément identifié, genre la photo de profil, l'image d'illustration d'une fiche, ...
Mais je ne peux pas sur les images de la galerie d'images, les illustrations pour les points clés, ...
