### ISSUE TITLE
Peut-on faire un header fixe ou  qui ré-apparaisse quand on scroll vers le haut ?

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#193]

**Comment by alexisben** [comment]
Il ne me semble pas que cela est été prévu ? @flogll ?

**Comment by flogll** [comment]
ce serait bien si possible mais relativement anecdotique pour finaliser la V1, c'est galère de mettre du sticky @pabois ?

**Comment by pabois** [comment]
c'rest @alexisben l'interlocuteur ici :-)

**Comment by alexisben** [comment]
Pas pour vendredi c'est trop tard

**Comment by alexisben** [comment]
fix https://github.com/noesya/ecotheque/pull/259
