### ISSUE TITLE
Lien interne entre les pages pas affichés

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#194]
Les liens internes entre les pages (dans fiche projet : fiche technique ou matériaux utilisés) n’apparaissent pas en fin de page publiée

Page lecture : https://www.ecotheque.fr/projets/rosa-bonheur

<img width="1137" alt="Capture d’écran 2024-03-25 à 16 02 37" src="https://github.com/noesya/ecotheque/assets/163397728/b31e6521-3c3d-4c73-a797-1b5e1ce4301e">

Page Ecriture Admin : 
<img width="1141" alt="Capture d’écran 2024-03-25 à 16 03 04" src="https://github.com/noesya/ecotheque/assets/163397728/69968415-c590-416b-a84a-a699086761f1">

Les liens ne s’affichent pas non plus dans la partie admin>lecture.

**Comment by pabois** [comment]
J'ai ajouté les techniques dans le show de l'admin

**Comment by Arthur-VilletteMakerz** [comment]
Mais actuellement elle s'affiche dans la catégorie l'étape "2. Réduction de la quantité de matière" par défaut ?
On devrait pouvoir choisir où elle s'affiche. C'est ce que l'on avait vu avec @flo

**Comment by pabois** [comment]
Actuellement ce qui est développé c'est que les matériaux s'affichent en fin d'étape 1 et les techniques en fin d'étape 2.
Je n'ai pas de moyen "simple" de les mettre en milieu d'étape.

**Comment by Arthur-VilletteMakerz** [comment]
Ce n'était pas de le mettre en milieu d'étape mais de pouvoir choisir sur quelle étape.
Est-ce qu'il est possible de mettre les technique sur l'étape 3 plutôt dans ce cas.

**Comment by pabois** [comment]
Donc matériaux en fin d'étape 1 (comme actuellement) et techniques en fin d'étape 3 ?

**Comment by Arthur-VilletteMakerz** [comment]
Yes

**Comment by flogll** [comment]
le choix d'étape n'avait finalement pas été retenu avec Sylvie @Arthur-VilletteMakerz, et on avait validé le principe avec matériaux en axe 1 et techniques en axe 2, on passe juste techniques en étape 3 donc
