### ISSUE TITLE
Case à cocher : Accord de validation 

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#195]
Il manque une coche importante en fin de Projets en back office : “J’ai obtenu les accords nécessaires au partage de ces informations et illustrations. J’accepte qu’elles soient utilisées pour la communication digitale de l’écothèque, dans un but de promotion de ce travail”. Pouvez-vous l’ajouter ? cela engage le contributeur·rice à informer ses collaborateurs. @J’ai obtenu tous les accords nécessaires au partage de ces informations.

**Comment by pabois** [comment]
@Arthur-VilletteMakerz 
Juste pour les fiches projets ?
Juste à la création de la fiche ?

**Comment by pabois** [comment]
En l'attente de plus d'info j'ai fait ça, uniquement projet & création

**Comment by Arthur-VilletteMakerz** [comment]
Hello,
Oui, juste a la création de la fiche projet
