### ISSUE TITLE
Bloc Fichiers

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#198]
Trop d’informations quasi similaires : entre nom, titre, titre du fichier et le titre original du fichier importé ; possible de virer le titre et/ou que le titre original du fichier ne s’affiche pas ?

**Comment by pabois** [comment]
C'est les champs nécessaires pour appliquer la maquette.
On peut supprimer le nom original mais ça change la maquette !

**Comment by flogll** [comment]
Enlevons le titre original dans ce cas
