### ISSUE TITLE
Édition dans bloc accordéon

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#199]
Il y a encore des bugs dans le bloc Accordéon : les boutons gras et italique ne fonctionnent pas (mais ça marche avec les raccourcis clavier) ; les bullet points buggent pas mal aussi, à la fois en édition dans le back office mais aussi à l’affichage en front (cf capture)
<img width="673" alt="Capture d’écran 2024-03-25 à 16 18 33" src="https://github.com/noesya/ecotheque/assets/163397728/ca7e7212-830e-4891-b11f-5651f82a2011">

**Comment by alexisben** [comment]
Peux-tu me donner une url stp ?

**Comment by pabois** [comment]
@Arthur-VilletteMakerz ça doit être mieux maintenant.
Les boutons marchent à nouveau
