### ISSUE TITLE
Liens html invisibles dans bloc Points clés (Pages / Boîte à outils)

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#200]
Il faut paramétrer pour que la typo des liens soit blanche comme le texte car actuellement je pense que c’est de la même couleur que le fond gris ce qui les rend invisibles

**Comment by alexisben** [comment]
As-tu une url stp ?

**Comment by Arthur-VilletteMakerz** [comment]
Dernier bloc de cette page : https://www.ecotheque.fr/boite-a-outils/travaux-du-lab/ignifugation-alternatives/1-historique-et-enjeux

**Comment by SebouChu** [comment]
Le correctif est en cours de déploiement !
