### ISSUE TITLE
Vues régions 

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#203]
Passer l'image d'illustration en vue ouverte au format carré pour éviter le rognage (modif maquette demain) 

lien : https://www.ecotheque.fr/ile-de-france

**Comment by flogll** [comment]
le souci c'était le format rectangulaire de l'illu de région qui d'après Théophile rognait certaines d'entre-elles et effectivement c'était pas très malin vu que les vignettes en index de région sont carrées donc autant passer sur du format carré partout
![image](https://github.com/noesya/ecotheque/assets/37301562/129538e8-b3e7-4351-9c20-1b6ce9da1f06)

**Comment by flogll** [comment]
il faudrait ajouter la possibilité de crop lors de l'ajout de l'illu dans le BO comme pour les fiches

**Comment by alexisben** [comment]
Je comprends pas, pourquoi ne pas mettre des images carrées ?

**Comment by pabois** [comment]
j'ai mis le cropper, mais il ne fonctionne pas pour des svg !
Donc retour au plan d'alex, faut envoyer des images carrées (mais on maitrise normalement, les régions c'est que pour les admins !)
