### ISSUE TITLE
Affichage page Contact

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#206]
J’ai testé 2 options aucune n’est satisfaisante (cf captures d’écran) : soit pas possibilité édition bloc de texte de description (donc aucun retour à la ligne…) soit j’ajoute des blocs de texte hors description mais cela crée un énorme espace entre le titre et le premier bloc
<img width="989" alt="Capture d’écran 2024-03-26 à 11 04 55" src="https://github.com/noesya/ecotheque/assets/163397728/11d24fa0-f637-4943-986c-6bc8ee7ad671">
<img width="986" alt="Capture d’écran 2024-03-26 à 11 05 07" src="https://github.com/noesya/ecotheque/assets/163397728/5e68f2f9-a872-4396-a3f9-47de79ec48b2">

**Comment by pabois** [comment]
La bonne option c'est la 2ème.
il faut supprimer cet espace quand il n'y a pas de description !

@alexisben tu peux stp ?

**Comment by alexisben** [comment]
Ça fait un cas particulier pour un hero, je propose plutôt de passer le corps du document sur fond blanc.

**Comment by alexisben** [comment]
![image](https://github.com/noesya/ecotheque/assets/4630530/e6da23ac-8af0-4538-bb1d-c93b101cfa29)

**Comment by alexisben** [comment]
j'ai passé le hero des pages par défaut en fond blanc.
