### ISSUE TITLE
inté HP

### ISSUE THREAD

**Issue by flogll** [noesya/ecotheque#210]
### Desktop
- [x] augmenter la taille du h1 à 5rem au lieu de 4 pour "La plateforme collaborative de l'écoscénographie", un peu petit acctuellement comparé à la maquette

- [x] reprendre les paddings verticaux des blocs citations des pages édito pour la section citation de la HP, actuellement elle est un peu fine je trouve. Lien ref de droite : https://www.ecotheque.fr/boite-a-outils/travaux-du-lab/ignifugation-alternatives 
![image](https://github.com/noesya/ecotheque/assets/37301562/7c1f507d-d6eb-4df4-b2dd-16e9488da70e)

### Mobile
- [x] augmenter l'espace vertical entre zone de recherche et "Ou explorer nos annuaires", idem entre ce dernier et "un projet portépar l'augureslab"
![image](https://github.com/noesya/ecotheque/assets/37301562/cb02f371-d27c-42e1-aabd-dae824763962)

- [ ] la zone d'interaction qui redirige vers l'annuaire doit être tout en bas. Laisser le grand chiffre de la taille actuelle en revanche, c'était trop petit en maquette en y rejetant un oeil.
- [x] réduire la marge verticale au-dessus du titre des tranches des 4 annuaires et boîte à outils
![image](https://github.com/noesya/ecotheque/assets/37301562/cfab3b24-6ec9-4b2f-a967-1207d89579ed)

**Comment by alexisben** [comment]
Pour ce point :
>  la zone d'interaction qui redirige vers l'annuaire doit être tout en bas. Laisser le grand chiffre de la taille actuelle en revanche, c'était trop petit en maquette en y rejetant un oeil.

C'est compliqué car la structure et l'ordre des éléments diffèrent de la version desktop
