### ISSUE TITLE
Le chargement des images est parfois (très) lent, selon la puissance de la machine, la connexion 

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#213]
Peut-on passer de max 5Mo à max 2Mo ? ça éviterait des temps d’attente très long.

**Comment by pabois** [comment]
On peut, mais ça me semble assez peu. Notamment si il y a des pdfs explicatifs avec de l'image, 2Mo ça va être juste.

Vous me confirmez ce choix ?

@Arthur-VilletteMakerz

**Comment by pabois** [comment]
Cette issue est ouverte depuis el lancement. Ca à l'air de bien se passer en prod.
Je close
