### ISSUE TITLE
Métadonnées

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#218]
il n’y a aucune métadonnée de rentrée donc quand on partage le site il n’y a rien… Possible svp de prévoir une image (celle de la page d’accueil) et un texte (a minima : écothèque, la plateforme collaborative de l’écoscénographie)

**Comment by alexisben** [comment]
@pabois tu veux baser le contenu de la meta description des pages sur quoi ?

**Comment by alexisben** [comment]
Il n'y a pas d'image sur la page d'accueil, est-ce qu'on parle de faire un screenshot de l'en-tête de la page d'accueil ?

**Comment by Arthur-VilletteMakerz** [comment]
Ah oui en effet... C'est possible de faire un screen ? Quels sont les solutions techniques ?
