### ISSUE TITLE
Nous rejoindre > Finaliser contenu

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#220]
**1. Texte de description :**

**Les offres**

Certains contenus de l’écothèque sont accessibles librement, comme les annuaires Écosystème, Projets ainsi que la Boîte à outils avec tous les Travaux du Lab. Pour contribuer et recevoir nos actualités, vous pouvez créer un compte gratuitement. Pour avoir accès à l’intégralité des contenus et à quelques fonctionnalités supplémentaires sur votre compte, une offre d’abonnement est disponible, allant de 5€ pour les étudiant·es à 1500€ pour les structures de plus de 25 salarié·es. Si vous êtes intéressé·e de devenir membre de l’Augures Lab Scénogrrrraphie et contribuer au travail de recherche-action, n’hésitez pas à vous inscrire à l’une de nos réunions d’information mensuelles. Si votre intérêt est de rendre votre activité plus visible sur l’écothèque, deux offres sont disponibles : essentiel (contenus augmentés sur l’écothèque) et premium (mise en relation avec les membres du Lab).

Retrouvez ci-dessous le détail des offres d’accès et de visibilité à l’écothèque.  

**2. Pourquoi nous rejoindre :**
![Pourquoi nous rejoindre](https://github.com/noesya/ecotheque/assets/163397728/058ed566-04b3-4bba-bd66-f508e6b56e43)

**3. Galerie photos :**

L’enlever pour l’afficher plutôt sur la page Le Lab et que nous puissions l’éditer en interne. Là ça ne va pas en l’état, il y a 2 fois les mêmes photos et les légendes sont fausses

**Comment by flogll** [comment]
sur le pourquoi nous rejoindre ça va pas, j'avais prévenu Caro qu'il fallait utiliser les points clés comme prévu en évitant les titres à rallonge comme ça. 

Ok pour enlever la gallerie mais une fois de plus elle avait été validée telle quelle...

**Comment by pabois** [comment]
@flogll @Arthur-VilletteMakerz 
j'ai enlevé la galerie.
J'ai mis les textes comme suggéré par Florian.
Il me manque les icônes !

**Comment by pabois** [comment]
c'est ok
