### ISSUE TITLE
Mobile > Logos Footer > Basse définition

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#234]
3 logos apparaissent très flou sur mobile dans le footer : Région, Préfet et Les Augures

![IMG_2855](https://github.com/noesya/ecotheque/assets/163397728/cdeca047-ba64-4cb2-8dc7-261abf6116d0)

**Comment by SebouChu** [comment]
@flogll

**Comment by pabois** [comment]
@Arthur-VilletteMakerz
