### ISSUE TITLE
Nouveau problème multi-filtre

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#240]
je cherche un matériaux en "impression" et "rigide", le lanisor devrait ressortir mais ça n'est pas le cas...

**Comment by pabois** [comment]
ca marche chez moi
https://www.ecotheque.fr/materiaux?facets&facets[usage-preconise]=impression&facets[proprietes-techniques]=rigide#results

**Comment by pabois** [comment]
<img width="1197" alt="Capture d’écran 2024-03-28 à 13 07 06" src="https://github.com/noesya/ecotheque/assets/2145137/2d25f942-f6e8-4202-949d-555835a7d46c">

**Comment by Arthur-VilletteMakerz** [comment]
Ah oui, c'est un problème de filtre, il y a rigide dans "Aspect esthétique" et "propriété physique"
