### ISSUE TITLE
Région > Affichage de 7 acteur·ices dans la "Région Pays de la Loire" mais seulement 4 fiches Écosystème apparentes. Est-ce normal ?

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#242]
<img width="1440" alt="Capture d’écran 2024-03-28 à 16 27 19" src="https://github.com/noesya/ecotheque/assets/163397728/376ec389-8440-42b1-8297-ab73f7d5acfc">

**Comment by pabois** [comment]
Alors l'affichage ici est volontairement limité à 4.
C'est @arnaudlevy qui a fait ça, mais je ne sais pas pourquoi :)
Il vaudrait sans doute mieux des paginations ?

**Comment by Arthur-VilletteMakerz** [comment]
Oui, ou un bouton pour accéder à la vue complète

**Comment by pabois** [comment]
Les titres sont déjà cliquables, mais je rajoute des liens explicites en dessous

**Comment by arnaudlevy** [comment]
Je crois qu'il y avait 4 de chaque à un moment dans les maquettes mais j'ai peut-être rêvé
