### ISSUE TITLE
Spinner qui reste affiché

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/ecotheque#246]
https://www.ecotheque.fr/admin/pages/c6f4fdfc-ee6e-45f6-8d5c-dbce2ee82e9e/blocks/ff625795-ade6-4c6b-814f-85d7a066470a/edit

<img width="1792" alt="Capture d’écran 2024-03-28 à 21 12 21" src="https://github.com/noesya/ecotheque/assets/2088968/1e4705b6-6988-415e-94fd-38a6d16b1193">

**Comment by SebouChu** [comment]
je reproduis pas

**Comment by arnaudlevy** [comment]
ce matin c'est ok (cache ?)
