### ISSUE TITLE
Filtres

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#248]
Dans les filtres je sélectionne 
USAGE PRECONISE  >  Impression 
PROPPIETES TECHNIQIES. > Léger
J'ai 5 résultats cohérents
Si j'aoute dans PROPRIETES TECHNIQUES. > Rigide
Dans les résultats est ajouté Greencast alors qu'il n'est pas léger et est conservé CAPOTOILE alors qu'il n'est pas Rigide

**Comment by SebouChu** [comment]
Au sein d'un même filtre, c'est un "OU" et pas un "ET"

Donc ta recherche cible les matériaux avec :
- usage préconisé : Impression
- propriétés techniques : léger OU rigide

**Comment by Arthur-VilletteMakerz** [comment]
Ok, merci pour le retour !
