### ISSUE TITLE
Ajouter un texte explicatif sous “le mot du comité ecothèque”

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#268]
“Vous pouvez ajouter ici votre expérience du service/produit et le comité écothèque en fera en relecture et une ré-écriture”

**Comment by pabois** [comment]
@Arthur-VilletteMakerz On parle bien d'afficher ça dans le BO sous les champs "Le mot du comité" ?
Ces champs sont présents pour les 4 types de fiche, le texte à ajouter me semble ne pas concerner les 4.

**Comment by Arthur-VilletteMakerz** [comment]
C'est bien ça et c'est bien a ajouter sous les 4 types de fiches.
Si possible en effet de mettre : 
...votre expérience du matériau
...votre expérience de la technique
...votre avis personnel sur l'acteur·ice
...votre avis personnel sur le projet
