### ISSUE TITLE
Légendes Photos

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#269]
Paramétrer un retour à la ligne quand la légende est trop longue (cf capture d’écran)
<img width="1266" alt="Capture d’écran 2024-04-11 à 18 43 45" src="https://github.com/noesya/ecotheque/assets/163397728/f3b1fec1-ff14-4730-9375-5ec8f83a87a0">

**Comment by pabois** [comment]
Exemple aussi dans le diaporama de cette page : 
https://www.ecotheque.fr/projets/atelier-rodin
