### ISSUE TITLE
Définition > Balise de code qui apparraissent <br

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#277]
![image](https://github.com/noesya/ecotheque/assets/163397728/14d65139-deb6-4b35-95ea-78164ec46237)

![image](https://github.com/noesya/ecotheque/assets/163397728/6215a5a2-8e99-4ad0-9c60-8c09afc9b074)

**Comment by pabois** [comment]
@Arthur-VilletteMakerz j'ai activé la prise en charge du html dans la tooltip, mais par contre l'éditeur en BO est un éditeur de texte simple. Vous pouvez mettre du html dedans (comme vous avez fait)
