### ISSUE TITLE
Bug “Prestations proposée” et fiches concernées

### ISSUE THREAD

**Issue by Arthur-VilletteMakerz** [noesya/ecotheque#284]
**Bug fiche de la Ressourcerie culturelle :** 

⇒ Le texte en dessous des tags (celui où il n’y a pas de mise en forme) n’est visible nul part sur le BO.
<img width="1440" alt="Untitled" src="https://github.com/user-attachments/assets/b8aecde3-9271-415d-823e-900a3b8c3821">

⇒ Par contre, ce texte est visible et modifiable.
<img width="1440" alt="Untitled (1)" src="https://github.com/user-attachments/assets/fe0dc07c-9d57-4f55-b230-bdfe29aab3ec">

Même problème sur autres fiches : 

- Rotor
- Rotor DC
- WAAO
- Scierie de Luzy
- Scierie Brizard
- Open Lande
- RESSAC
- Réserve des Arts Pantin

**Comment by pabois** [comment]
Hello @Arthur-VilletteMakerz 

Bien vu.
Le problème vient du champ d'explications qui était actif précédemment, et qui a été rempli.
il a ensuite été désactivé mais le texte rentré dedans y est toujours, et continue à s'afficher.
On corrige ça pour ne plus afficher le texte si l'option est désactivée
