### ISSUE TITLE
To do list intégration

### ISSUE THREAD

**Issue by Olivia206** [noesya/ecotheque#68]
Global : 

Recherche : 
- [x] La recherche dans la modal
- [x] Page de recherche
- [x] Gérer le cas de l'absence de résultat en affichant liens vers annuaires

- [x] Annuaire : recherche sur la carte
- [x] Fiche projet : revoir la roue de brezet
- [x] Fiche membre
- [x] Glossaires - Index
- [x] Glossaire - Mot (sur le modèle de l'index d'un annuaire) 
- [ ] Fiches : définitions au survol d'un mot dans une modale

- [x] Pages régions

Pages statiques :
- [x] Bloc citation
- [x] Bloc chapite
- [x] Bloc fonctionnalités (horizontal et vertical ?)
- [x] Bloc images
- [x] Bloc FAQ (accordéons)

- [x] Pages souscription

- [x] Page user : image de profil
- [x] Commentaires : image de profil

- [x] Paywall
- [x] Modale inscription/redirection offres -> en cliquant sur le cta de l'annuaire ?

Mobile : 

- [x] Le menu

**Comment by alexisben** [comment]
- [ ] Réponse à un commentaire
- [ ] Filtre "Trier par" : attente réponse CTRL S
- [ ] Filtre accordéon
- [ ] Filtre "recherche nom" pas correctement intégré

**Comment by Olivia206** [comment]
Liens à brancher : 

- [ ] Footer
- [ ] cta référencement
